version: '3.7'
services:
  # frontend:

  api:
  # build: thư mục chứa backend (./services/backend)
    build: .
    ports:
     - "8000:8000"
    working_dir: /app
    volumes:
     - ./:/app
  # postgres:
  #   image: postgres:12.1-alpine
      # ports:
      #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=movie_db_username
  #     - POSTGRES_PASSWORD=movie_db_password
  #     - POSTGRES_DB=movie_db_dev
#   nginx:
#     image: nginx:latest
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - cast_service
#       - movie_service

# volumes:
#   postgres_data:

