version: '3.7'
services:
  fontend:
    container_name: fontend
    build: ./fontend
    ports:
      - "8080:8080"
    working_dir: /app_ba
    volumes:
      - ./:/app_ba
  api:
    container_name: api
    build: ./backend
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - "3307:3306"
    hostname: db
    env_file:
      - ./.env
    restart: always
    volumes:
      - database:/var/lib/mysql
volumes:
  database:

